spring:
  application:
    name: monew
  datasource:
    url: jdbc:postgresql://${DB_HOST:database-1.c5aoku0giqzs.ap-northeast-2.rds.amazonaws.com}:${DB_PORT:5432}/
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:monew1234!}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb://localhost:27017/monew
      port: 27017
      database: monew
  batch:  # batch 관련 테이블 자동 생성을 위한 설정
    jdbc:
      initialize-schema: never
  # batch 시간 job1 = backup시간 , job2 = article등록 시간  (초 분 시 일 월 요일)
  backup:
    job1:
      cron: "0 43 9 * * *"
    job2:
      cron: "0 42 9 * * *"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  sql:
    init:
      mode: always          # 항상 실행 (none, embedded, always 중 always 선택)
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION:ap-northeast-2}
  s3:
    bucket: ${AWS_S3_BUCKET:monew-1234}
    prefix: ${AWS_S3_PREFIX:uploads}

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

CLIENT_SECRET: ${CLIENT_SECRET:MJJpvWwVXY}
