spring:
  application:
    name: monew
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  data:
    mongodb:
      uri: mongodb+srv://monew:monew1234@monew.njspvcb.mongodb.net/?appName=monew
      database: monew
  batch:  # batch 관련 테이블 자동 생성을 위한 설정
    jdbc:
      initialize-schema: never
  # batch 시간 job1 = backup시간 , job2 = article등록 시간  (초 분 시 일 월 요일)
  backup:
    job1:
      cron: "0 2 * * * *"
    job2:
      cron: "0 0 * * * *"
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 200MB
  sql:
    init:
      mode: always          # 항상 실행 (none, embedded, always 중 always 선택)
      schema-locations: classpath:schema.sql
#      data-locations: classpath:data.sql
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
server:
  port: 8080

aws:
  accessKeyId: ${AWS_ACCESS_KEY}
  secretKey: ${AWS_SECRET_KEY}
  region: ${AWS_REGION}
  s3:
    bucket: ${AWS_S3_BUCKET}
    prefix: uploads

logging:
  pattern:
    console: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,loggers,env,threaddump,heapdump,users
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true   # liveness/readiness
  info:
    env:
      enabled: true     # info. 노출
    java:
      enabled: true
    os:
      enabled: true
    build:
      enabled: true

CLIENT_SECRET: "K8gpcn9pFr"